export class ServerUtils {
  static a = 'a'
  static b = 'b'
  static c = 'c'
  static d = 'd'
  static e = 'e'
  static f = 'f'
  static g = 'g'
  static h = 'h'
  static i = 'i'
  static j = 'j'
  static k = 'k'
  static l = 'l'
  static m = 'm'
  static n = 'n'
  static o = 'o'
  static p = 'p'
  static q = 'q'
  static r = 'r'
  static s = 's'
  static t = 't'
  static u = 'u'
  static v = 'v'
  static w = 'w'
  static x = 'x'
  static y = 'y'
  static z = 'z'
  static A = 'A'
  static B = 'B'
  static C = 'C'
  static D = 'D'
  static E = 'E'
  static F = 'F'
  static G = 'G'
  static H = 'H'
  static I = 'I'
  static J = 'J'
  static K = 'K'
  static L = 'L'
  static M = 'M'
  static N = 'N'
  static O = 'O'
  static P = 'P'
  static Q = 'Q'
  static R = 'R'
  static S = 'S'
  static T = 'T'
  static U = 'U'
  static V = 'V'
  static W = 'W'
  static X = 'X'
  static Y = 'Y'
  static Z = 'Z'

  static N_1 = '1'
  static N_2 = '2'
  static N_3 = '3'
  static N_4 = '4'
  static N_5 = '5'
  static N_6 = '6'
  static N_7 = '7'
  static N_8 = '8'
  static N_9 = '9'
  static N_0 = '0'
  static colon = ':'
  static slash = '/'
  static dot = '.'
  static three = '3'
  static six = '6'
  static five = '5'

  /**
   * 返回 https://facai365.vip
   */
  static getHost() {
    return this.h + this.t + this.t + this.p + this.s + this.colon + this.slash + this.slash + this.f + this.a + this.c + this.a + this.i + this.three + this.six + this.five + this.dot + this.v + this.i + this.p
  }
}
